/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Subject = IDL.Record({
  'practicalDate' : IDL.Opt(IDL.Text),
  'examDate' : IDL.Text,
  'assignmentDetails' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Role = IDL.Variant({
  'admin' : IDL.Null,
  'invalid' : IDL.Null,
  'student' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllSubjectData' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, Subject))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getNotifications' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getRegisteredStudents' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'login' : IDL.Func([IDL.Text, IDL.Text], [Role], []),
  'register' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateChemistry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateMath' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateNotifications' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'updatePhysics' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Subject = IDL.Record({
    'practicalDate' : IDL.Opt(IDL.Text),
    'examDate' : IDL.Text,
    'assignmentDetails' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Role = IDL.Variant({
    'admin' : IDL.Null,
    'invalid' : IDL.Null,
    'student' : IDL.Null,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllSubjectData' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, Subject))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getNotifications' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getRegisteredStudents' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'login' : IDL.Func([IDL.Text, IDL.Text], [Role], []),
    'register' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateChemistry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateMath' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateNotifications' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'updatePhysics' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };