/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Role = { 'admin' : null } |
  { 'invalid' : null } |
  { 'student' : null };
export interface Subject {
  'marks' : string,
  'practicalDate' : [] | [string],
  'teacherEmail' : string,
  'attendanceTotal' : bigint,
  'teacherName' : string,
  'attendancePresent' : bigint,
  'progress' : bigint,
  'examDate' : string,
  'assignmentDetails' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAdminNote' : ActorMethod<[string, string, Principal], undefined>,
  'addNote' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllNotes' : ActorMethod<[string, Principal], Array<string>>,
  'getAllSubjectData' : ActorMethod<[], Array<[string, Subject]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCompletedAssignments' : ActorMethod<[], Array<string>>,
  'getNotes' : ActorMethod<[string], Array<string>>,
  'getNotifications' : ActorMethod<[], Array<string>>,
  'getRegisteredStudents' : ActorMethod<[], Array<string>>,
  'getScholarNumber' : ActorMethod<[string], [] | [string]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'login' : ActorMethod<[string, string], Role>,
  'loginByScholarNumber' : ActorMethod<[string, string], Role>,
  'markAssignmentComplete' : ActorMethod<[string], undefined>,
  'register' : ActorMethod<
    [string, string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'resetAllCourseData' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateChemistry' : ActorMethod<
    [string, string, string, string, string, bigint, bigint, bigint, string],
    undefined
  >,
  'updateMath' : ActorMethod<
    [string, string, string, string, bigint, bigint, bigint, string],
    undefined
  >,
  'updateNotifications' : ActorMethod<[Array<string>], undefined>,
  'updatePhysics' : ActorMethod<
    [string, string, string, string, string, bigint, bigint, bigint, string],
    undefined
  >,
  'updateSubjectExtended' : ActorMethod<
    [string, string, string, bigint, bigint, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];